export class Liste{
    //base = "http://haikintana-api.herokuapp.com"; 
    base = "http://127.0.0.1:8000";
    membre = "membres";
    mail = "mails";
    fb = "fbs";
    numero = "numeros";
    qrcode = "qrcode";
    categorie = "categories";
    activite = "activites";
    description = "descriptions";
    photo = "photos";
    presence = "presences";
    contactorganisation = "contactorganisations";
    photoprofil = "photoprofils";
    regle = "regles";
    cotisation = "cotisations";
    paiement = "paiements";
    statut = "statuts";
    authentification = "authentification";
    user = "users";
}